version: '2'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/common:/etc/nginx/common
    volumes_from:
      - php
    depends_on:
      - php
    environment:
      - TZ=Europe/Moscow
  php:
    container_name: php
    build: ./php
    volumes:
      - /home/neiron/www:/usr/share/nginx/www
      - /home/neiron/.ssh:/home/user/.ssh
    ports:
      - "4000:22"
    cap_add:
      - ALL
    dns:
      - 172.17.0.1
      - 8.8.8.8
    environment:
      - TZ=Europe/Moscow
  mysql:
    container_name: mysql
    build: ./mysql
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
  redis:
    container_name: redis
    image: redis
    environment:
      - TZ=Europe/Moscow